name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Run tests with coverage (fail if < 80%)
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
          awk '/total:/ { if ($3+0 < 80) { print "Coverage too low!"; exit 1 } }' coverage.out
